import { models } from '../index.js';
import { uploadVideoFile } from '../services/cloudflareR2Service.js';
import fs from 'fs/promises';

/**
 * Process automatic meeting recording when meeting ends
 * This should be called when:
 * 1. Host manually stops recording
 * 2. Meeting ends (last participant leaves)
 * 3. Room is closed by host
 */
export async function processAutoRecording(roomId, recordingData) {
  try {
    // Find the associated meeting
    const meeting = await models.Meeting.findOne({ roomId });
    if (!meeting) {
      console.error(`No meeting found for room: ${roomId}`);
      return null;
    }

    // Validate recording data
    if (!recordingData.filePath || !recordingData.duration) {
      console.error('Invalid recording data provided');
      return null;
    }

    // Generate automatic title
    const autoTitle = `${
      meeting.title || 'Meeting'
    } - ${new Date().toLocaleDateString()}`;

    // Read the recording file
    const recordingBuffer = await fs.readFile(recordingData.filePath);

    // Create recording document
    const recording = new models.MeetingRecording({
      meetingId: meeting._id,
      organizationId: meeting.organizationId,
      title: autoTitle,
      description: `Automatically recorded meeting: ${
        meeting.title || 'Untitled Meeting'
      }`,
      recording: {
        fileName: `meeting-${meeting.meetingId}-${Date.now()}.mp4`,
        fileSize: recordingBuffer.length,
        duration: recordingData.duration,
        format: 'mp4',
        quality: recordingData.quality || '720p',
        storageProvider: 'r2',
      },
      visibility: 'participants', // Default to participants-only for auto recordings
      tags: ['auto-recorded', 'meeting'],
      processingStatus: 'uploading',
      participants: [
        // Add host
        {
          userId: meeting.host.userId,
          role: 'host',
          joinTime: meeting.createdAt,
          speakingTime: recordingData.hostSpeakingTime || 0,
        },
        // Add participants who actually joined
        ...meeting.participants
          .filter((p) => p.joinedAt) // Only participants who actually joined
          .map((p) => ({
            userId: p.userId,
            role: 'participant',
            joinTime: p.joinedAt,
            speakingTime:
              recordingData.participantSpeakingTimes?.[p.userId] || 0,
          })),
      ],
      metadata: {
        recordingStartTime: recordingData.startTime,
        recordingEndTime: recordingData.endTime,
        actualDuration: recordingData.duration,
        roomId: roomId,
        meetingId: meeting.meetingId,
        autoGenerated: true,
      },
    });

    await recording.save();

    try {
      // Upload to Cloudflare R2
      const uploadResult = await uploadVideoFile(recordingBuffer, {
        fileName: `meeting_${meeting._id}.mp4`,
        organizationId: meeting.organizationId || 'personal',
        recordingId: recording._id.toString(),
        fileFormat: 'mp4',
      });

      // Update recording with R2 URLs
      recording.recording.storagePath = uploadResult.key;
      recording.recording.downloadUrl = uploadResult.downloadUrl;
      recording.recording.streamingUrl = uploadResult.streamingUrl;
      recording.recording.thumbnailUrl = uploadResult.thumbnailUrl;
      recording.recording.duration =
        uploadResult.duration || recordingData.duration;
      recording.processingStatus = 'completed';

      await recording.save();

      // Clean up local file
      try {
        await fs.unlink(recordingData.filePath);
      } catch (cleanupError) {
        // Failed to cleanup local file
      }

      // Start automatic AI processing in background
      // Don't await - let it process asynchronously
      setTimeout(() => {
        startAutoAIProcessing(recording._id).catch((error) => {
          console.error(
            `Auto AI processing failed for recording ${recording._id}:`,
            error
          );
        });
      }, 2000); // Small delay to ensure upload is complete

      return recording;
    } catch (uploadError) {
      console.error('R2 upload failed:', uploadError);

      // Update recording status to failed
      recording.processingStatus = 'failed';
      recording.errorMessage = `Upload failed: ${uploadError.message}`;
      await recording.save();

      throw uploadError;
    }
  } catch (error) {
    console.error('Auto recording processing failed:', error);
    throw error;
  }
}

/**
 * Start automatic AI processing for a recording
 * This includes both transcript and summary generation
 */
async function startAutoAIProcessing(recordingId) {
  try {
    const recording = await models.MeetingRecording.findById(recordingId);
    if (!recording || !recording.recording.streamingUrl) {
      console.error('Recording not found or no streaming URL available');
      return;
    }

    // Import AI processing function
    const { processRecordingAI } = await import('../routes/recordings.js');

    // Start both transcript and summary processing
    const processingId = `auto_${recordingId}_${Date.now()}`;

    // Update status to processing
    recording.transcript.status = 'processing';
    recording.aiSummary.status = 'processing';
    await recording.save();

    // Process in background
    await processRecordingAI(recording, 'both', processingId);
  } catch (error) {
    console.error('Auto AI processing failed:', error);

    // Update recording with error status
    try {
      const recording = await models.MeetingRecording.findById(recordingId);
      if (recording) {
        recording.transcript.status = 'failed';
        recording.aiSummary.status = 'failed';
        recording.transcript.errorMessage = error.message;
        recording.aiSummary.errorMessage = error.message;
        await recording.save();
      }
    } catch (updateError) {
      console.error('Failed to update recording error status:', updateError);
    }
  }
}

/**
 * Utility function to estimate file size limits based on user plan
 */
export function getRecordingLimits(userPlan = 'free') {
  const limits = {
    free: {
      maxFileSize: 100 * 1024 * 1024, // 100MB
      maxDuration: 60 * 60, // 1 hour
      maxRecordingsPerMonth: 10,
      maxStorageTotal: 1024 * 1024 * 1024, // 1GB
    },
    pro: {
      maxFileSize: 500 * 1024 * 1024, // 500MB
      maxDuration: 4 * 60 * 60, // 4 hours
      maxRecordingsPerMonth: 100,
      maxStorageTotal: 50 * 1024 * 1024 * 1024, // 50GB
    },
    enterprise: {
      maxFileSize: 2 * 1024 * 1024 * 1024, // 2GB
      maxDuration: 8 * 60 * 60, // 8 hours
      maxRecordingsPerMonth: -1, // unlimited
      maxStorageTotal: -1, // unlimited
    },
  };

  return limits[userPlan] || limits.free;
}

/**
 * Check if user can upload/record based on their plan limits
 */
export async function checkRecordingPermissions(
  userId,
  organizationId,
  fileSize,
  duration
) {
  try {
    // Get user's plan (this would come from organization or user model)
    // For now, we'll assume 'free' - this should be updated to check actual plan
    const userPlan = 'free'; // TODO: Get from organization.plan or user.plan

    const limits = getRecordingLimits(userPlan);

    // Check file size limit
    if (limits.maxFileSize > 0 && fileSize > limits.maxFileSize) {
      return {
        allowed: false,
        reason: `File size exceeds ${Math.round(
          limits.maxFileSize / (1024 * 1024)
        )}MB limit for ${userPlan} plan`,
        limit: limits.maxFileSize,
        current: fileSize,
      };
    }

    // Check duration limit
    if (limits.maxDuration > 0 && duration > limits.maxDuration) {
      return {
        allowed: false,
        reason: `Recording duration exceeds ${Math.round(
          limits.maxDuration / 3600
        )} hour limit for ${userPlan} plan`,
        limit: limits.maxDuration,
        current: duration,
      };
    }

    // Check monthly recordings limit
    if (limits.maxRecordingsPerMonth > 0) {
      const startOfMonth = new Date();
      startOfMonth.setDate(1);
      startOfMonth.setHours(0, 0, 0, 0);

      const monthlyCount = await models.MeetingRecording.countDocuments({
        organizationId: organizationId,
        createdAt: { $gte: startOfMonth },
      });

      if (monthlyCount >= limits.maxRecordingsPerMonth) {
        return {
          allowed: false,
          reason: `Monthly recording limit of ${limits.maxRecordingsPerMonth} reached for ${userPlan} plan`,
          limit: limits.maxRecordingsPerMonth,
          current: monthlyCount,
        };
      }
    }

    // Check total storage limit
    if (limits.maxStorageTotal > 0) {
      const totalStorage = await models.MeetingRecording.aggregate([
        { $match: { organizationId: organizationId } },
        { $group: { _id: null, total: { $sum: '$recording.fileSize' } } },
      ]);

      const currentStorage = totalStorage[0]?.total || 0;
      if (currentStorage + fileSize > limits.maxStorageTotal) {
        return {
          allowed: false,
          reason: `Storage limit of ${Math.round(
            limits.maxStorageTotal / (1024 * 1024 * 1024)
          )}GB would be exceeded for ${userPlan} plan`,
          limit: limits.maxStorageTotal,
          current: currentStorage,
          requested: fileSize,
        };
      }
    }

    return {
      allowed: true,
      limits,
      usage: {
        // This could include current usage stats
      },
    };
  } catch (error) {
    console.error('Error checking recording permissions:', error);
    return {
      allowed: false,
      reason: 'Error checking permissions',
      error: error.message,
    };
  }
}
